spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://mysql:3306/movie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
    poster: posters/
base:
   url: "http://localhost:8080"

